// Antecedentes médicos de la ficha real (Historia Clínica de Dentar Devoto).
export const CONDICIONES_MEDICAS = [
  { key: 'alcoholismo', label: 'Alcoholismo' },
  { key: 'alergias', label: 'Alergias' },
  { key: 'anemia', label: 'Anemia' },
  { key: 'asma', label: 'Asma' },
  { key: 'hipertension', label: 'Hipertensión' },
  { key: 'herpes', label: 'Herpes' },
  { key: 'sinusitis', label: 'Sinusitis' },
  { key: 'tbc', label: 'Tbc' },
  { key: 'cefaleas', label: 'Cefaleas' },
  { key: 'droga_dependencia', label: 'Droga dependencia' },
  { key: 'epilepsia', label: 'Epilepsia' },
  { key: 'glaucoma', label: 'Glaucoma' },
  { key: 'tromboembolismo', label: 'Tromboembolismo' },
  { key: 'problemas_cardiacos', label: 'Problemas cardíacos' },
  { key: 'hiv', label: 'H.I.V.' },
  { key: 'fiebre_reumatica', label: 'Fiebre reumática' },
  { key: 'venereas', label: 'Venéreas' },
  { key: 'hepatitis', label: 'Hepatitis' },
  { key: 'tumores', label: 'Tumores' },
  { key: 'diabetes', label: 'Diabetes' },
  { key: 'hepaticas', label: 'Hepáticas' },
  { key: 'enf_endocrinas', label: 'Enf. endocrinas' },
  { key: 'vesiculares', label: 'Vesiculares' },
  { key: 'respiratorios', label: 'Respiratorios' },
  { key: 'ulceras', label: 'Úlceras' },
  { key: 'renales', label: 'Renales' },
  { key: 'otras', label: 'Otra/s' },
]
